---
title: "Seperate working file"
author: "Sara Kiros, Ohnmar Khine Min, Chen Su"
format: 
  html:
    highlight-style: espresso
    code-fold: true
execute: 
  eval: true
  echo: true
  warning: false
fig-width: 6.5
fig-height: 8
---


### 0. Loading Packages and Data

```{r}
#| label: load-packages-raw-data

library(tidyverse)
library(here)
library(rio)
library(janitor)
library(ggplot2)
library(dplyr)

pwave5 <- import(here("data", "pwave5.xpt")) |>
  characterize() |>
  clean_names() 

```


```{r}
#| label: select-variables

wave5_raw <- pwave5 |>
     select(aid, imonth5, iyear5, h5od1m, h5od1y,
            h5od2a, h5od3, h5od4a, h5od4b, h5od4c,
            h5od4d, h5od4e, h5od4f, h5od4g, h5od8,
            h5lm5, h5lm6, h5lm7, h5lm9, h5ec1, h5ec2,
            h5id9, h5id10a, h5id10b, h5id10c, h5id10d)

```


### 1. 
**Health Insurance Status**
```{r}
#Factoring 


library(dplyr)

# Factor: Health insurance status (Q9)
wave5_raw <- wave5_raw %>%
  mutate(
    h5id9 = factor(
      h5id9,
      levels = c(1, 2, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15),
      labels = c(
        "I get insurance through work",
        "I get insurance through a union",
        "I am covered by my spouse’s or partner’s insurance",
        "I am covered because I am active duty military",
        "I buy private insurance myself",
        "I buy insurance through a Health Insurance Marketplace or Exchange (ACA)",
        "I am on Medicaid",
        "I am on Medicare",
        "I get care through the Department of Veterans Affairs",
        "I am covered through TRI-CARE, CHAMPUS, CHAMP-VA, or other military plan",
        "I am covered through the Indian Health Service",
        "I do not know what my health insurance is",
        "I have no health insurance"
      )
    )
  )

# Factor: Q10 reasons (0 = no, 1 = yes, 97 = legitimate skip)
wave5_raw <- wave5_raw %>%
  mutate(across(
    c(h5id10a, h5id10b, h5id10c, h5id10d),
    ~ factor(.,
             levels = c(0, 1, 97),
             labels = c("no", "yes", "legitimate skip"))
  ))




```



```{r}

wave5_raw <- wave5_raw %>%
  mutate(
    h5ec2 = factor(
      h5ec2,
      levels = 1:13,
      labels = c(
        "Less than $5,000",
        "$5,000 to $9,999",
        "$10,000 to $14,999",
        "$15,000 to $19,999",
        "$20,000 to $24,999",
        "$25,000 to $29,999",
        "$30,000 to $39,999",
        "$40,000 to $49,999",
        "$50,000 to $74,999",
        "$75,000 to $99,999",
        "$100,000 to $149,999",
        "$150,000 to $199,999",
        "$200,000 or more"
      )
    )
  )


```

#Renaming Columns 
```{r}



wave5_clean <- wave5_raw %>%
  rename(
    insurance_status = h5id9,
    reason_a_not_offered_thru_work_or_school = h5id10a,
    reason_b_too_expensive = h5id10b,
    reason_c_no_need_or_want = h5id10c,
    reason_d_denied_insurance = h5id10d,
    household_income = h5ec2
  )

#colnames(wave5_raw)

```



```{r}

geom_col


```










